import { Course } from '../../types';

export const Html & css: Course = {
    id: "html11-course",
    slug: "html11",
    title: "curso html",
    description: "Descrição automática gerada pelo script.",
    thumbnail: "/images/html11-thumb.jpg",
    categories: [
        { 
            name: "Todos os Módulos", 
            moduleIds: ["html11-Module-1", "html11-Module-2", "html11-Module-3", "html11-Module-4", "html11-Module-5", "html11-Module-6", "html11-Module-7", "html11-Module-8", "html11-Module-9", "html11-Module-10", "html11-Module-11", "html11-Module-12", "html11-Module-13", "html11-Module-14", "html11-Module-15", "html11-Module-16", "html11-Module-17", "html11-Module-18", "html11-Module-19", "html11-Module-20"]
        }
    ],
    modules: [
        {
            id: "html11-Module-1",
            title: "1. Introdução (Assista antes de começar)",
            lessons: [
                { id: "html11-F001", title: "1. Como assistir as aulas" },
                { id: "html11-F002", title: "2. Como tirar suas dúvidas" },
                { id: "html11-F003", title: "3. Como baixar os arquivos e a apostila" },
                { id: "html11-F004", title: "4. Como emitir o certificado" },
                { id: "html11-F005", title: "5. Como funciona a garantia" },
                { id: "html11-F006", title: "6. Suporte Hashtag" },
                { id: "html11-F007", title: "7. Grupo do Facebook do HTML e CSS Impressionador" }
            ],
        },
        {
            id: "html11-Module-2",
            title: "2. Boas vindas e configurações iniciais",
            lessons: [
                { id: "html11-F008", title: "1. O que é Desenvolvimento Web" },
                { id: "html11-F009", title: "2. Baixando e configurando nosso editor de códigos" },
                { id: "html11-F010", title: "3. 2 dicas para todo programador" }
            ],
        },
        {
            id: "html11-Module-3",
            title: "3. Introdução ao HTML",
            lessons: [
                { id: "html11-F011", title: "1. O que é o HTML" },
                { id: "html11-F012", title: "2. Estrutura de um documento HTML" },
                { id: "html11-F013", title: "3. Elementos de texto" },
                { id: "html11-F014", title: "4. Ênfase, Importância e Formatação de Textos" },
                { id: "html11-F015", title: "5. Listas ordenadas e não ordenadas" },
                { id: "html11-F016", title: "6. Hiperlinks" },
                { id: "html11-F017", title: "7. Imagens e seus atributos no HTML" },
                { id: "html11-F018", title: "8. Ferramentas do Programador" },
                { id: "html11-F019", title: "9. Desafio 1 - Apresentando o Desafio" },
                { id: "html11-F020", title: "10. Desafio 1 - Construindo o Desafio do Zero" },
                { id: "html11-F021", title: "11. Desafio 2 - Home da Hashtag Treinamentos" },
                { id: "html11-F022", title: "12. Desafio 2 - Criando o Cabeçalho" },
                { id: "html11-F023", title: "13. Desafio 2 - Criando a Seção Hero" },
                { id: "html11-F024", title: "14. Desafio 2 - Criando a Seção Conteúdos Gratuitos" },
                { id: "html11-F025", title: "15. Desafio 2 - Criando a Seção Diferenciais" },
                { id: "html11-F026", title: "16. Desafio 2 - Criando a Seção O que falam" },
                { id: "html11-F027", title: "17. Desafio 2 - Criando a Seção Na mídia" },
                { id: "html11-F028", title: "18. Desafio 2 - Criando a Seção Blog da Hashtag" },
                { id: "html11-F029", title: "19. Desafio 2 - Criando a Seção Como ajudar" },
                { id: "html11-F030", title: "20. Desafio 2 - Criando a Seção Minicurso" },
                { id: "html11-F031", title: "21. Desafio 2 - Criando o Rodapé" }
            ],
        },
        {
            id: "html11-Module-4",
            title: "4. Introdução ao CSS",
            lessons: [
                { id: "html11-F032", title: "1. O que é CSS" },
                { id: "html11-F033", title: "2. As três formas de escrever CSS" },
                { id: "html11-F034", title: "3. Seletores no CSS" },
                { id: "html11-F035", title: "4. Combinando seletores" },
                { id: "html11-F036", title: "5. Estilizando textos" },
                { id: "html11-F037", title: "6. Trabalhando com cores" },
                { id: "html11-F038", title: "7. Estilizando hiperlinks" },
                { id: "html11-F039", title: "8. Desafio 1 - Formatando uma página em HTML" },
                { id: "html11-F040", title: "9. Desafio 1 - Resolvendo o Desafio" },
                { id: "html11-F041", title: "10. Desafio 2 - Formatando a Home da Hashtag" },
                { id: "html11-F042", title: "11. Desafio 2 - Formatando o Cabeçalho" },
                { id: "html11-F043", title: "12. Desafio 2 - Formatando a Seção Hero" },
                { id: "html11-F044", title: "13. Desafio 2 - Formatando a Seção Conteúdos Gratuitos" },
                { id: "html11-F045", title: "14. Desafio 2 - Formatando a Seção Diferenciais" },
                { id: "html11-F046", title: "15. Desafio 2 - Formatando a Seção O que falam" },
                { id: "html11-F047", title: "16. Desafio 2 - Formatando a Seção Na mídia" },
                { id: "html11-F048", title: "17. Desafio 2 - Formatando a Seção Blog da Hashtag" },
                { id: "html11-F049", title: "18. Desafio 2 - Formatando a Seção Como ajudar" },
                { id: "html11-F050", title: "19. Desafio 2 - Formatando a Seção Minicurso" },
                { id: "html11-F051", title: "20. Desafio 2 - Formatando o Rodapé" }
            ],
        },
        {
            id: "html11-Module-5",
            title: "5. Aprofundando no HTML",
            lessons: [
                { id: "html11-F052", title: "1. Apresentação do Módulo" },
                { id: "html11-F053", title: "2. Citações, Abreviações e Detalhes de contato" },
                { id: "html11-F054", title: "3. Códigos e Datas" },
                { id: "html11-F055", title: "4. Entrando mais a fundo na estrutura dos documentos" },
                { id: "html11-F056", title: "5. Formulários" },
                { id: "html11-F057", title: "6. Tabelas" },
                { id: "html11-F058", title: "7. iFrames" },
                { id: "html11-F059", title: "8. Desafio 1 - Apresentando o Desafio" },
                { id: "html11-F060", title: "9. Desafio 1 - Construindo juntos" },
                { id: "html11-F061", title: "10. Desafio 2 - Explicando as novidades" },
                { id: "html11-F062", title: "11. Desafio 2 - Completando o Cabeçalho" },
                { id: "html11-F063", title: "12. Desafio 2 - Completando a Seção Hero" },
                { id: "html11-F064", title: "13. Desafio 2 - Completando a Seção Conteúdos Gratuitos" },
                { id: "html11-F065", title: "14. Desafio 2 - Completando a Seção Diferenciais" },
                { id: "html11-F066", title: "15. Desafio 2 - Completando a Seção O que falam e Na mídia" },
                { id: "html11-F067", title: "16. Desafio 2 - Completando a Seção Blog da Hashtag" },
                { id: "html11-F068", title: "17. Desafio 2 - Completando a Seção Como ajudar" },
                { id: "html11-F069", title: "18. Desafio 2 - Completando a Seção Minicurso" },
                { id: "html11-F070", title: "19. Desafio 2 - Completando o Rodapé" }
            ],
        },
        {
            id: "html11-Module-6",
            title: "6. Aprofundando no CSS",
            lessons: [
                { id: "html11-F071", title: "1. Apresentação do Módulo" },
                { id: "html11-F072", title: "2. Especificidade no CSS" },
                { id: "html11-F073", title: "3. Trabalhando com espaçamentos" },
                { id: "html11-F074", title: "4. Dimensões e unidades no CSS" },
                { id: "html11-F075", title: "5. Pseudo-classes" },
                { id: "html11-F076", title: "6. Pseudo-elementos" },
                { id: "html11-F077", title: "7. Seletor universal e herança de estilos" },
                { id: "html11-F078", title: "8. Box Model no CSS" },
                { id: "html11-F079", title: "9. Sombras" },
                { id: "html11-F080", title: "10. Elementos arredondados" },
                { id: "html11-F081", title: "11. Tipos de visualização" },
                { id: "html11-F082", title: "12. Tipos de posicionamento" },
                { id: "html11-F083", title: "13. Background Color e Image" },
                { id: "html11-F084", title: "14. Desafio 1 - Evoluindo a página de Exercício" },
                { id: "html11-F085", title: "15. Desafio 1 - Gabarito" },
                { id: "html11-F086", title: "16. Desafio 2 - Aprofundando no Desafio 2" },
                { id: "html11-F087", title: "17. Desafio 2 - Aprofundando o Cabeçalho" },
                { id: "html11-F088", title: "18. Desafio 2 - Aprofundando a Seção Hero" },
                { id: "html11-F089", title: "19. Desafio 2 - Aprofundando a Seção Conteúdos Gratuitos" },
                { id: "html11-F090", title: "20. Desafio 2 - Aprofundando a Seção Diferenciais" },
                { id: "html11-F091", title: "21. Desafio 2 - Aprofundando a Seção O que falam" },
                { id: "html11-F092", title: "22. Desafio 2 - Aprofundando a Seção Na mídia" },
                { id: "html11-F093", title: "23. Desafio 2 - Aprofundando a Blog da Hashtag" },
                { id: "html11-F094", title: "24. Desafio 2 - Aprofundando a Seção Como ajudar" },
                { id: "html11-F095", title: "25. Desafio 2 - Aprofundando a Seção Minicurso" },
                { id: "html11-F096", title: "26. Desafio 2 - Aprofundando o Rodapé" }
            ],
        },
        {
            id: "html11-Module-7",
            title: "7. Flexbox no CSS",
            lessons: [
                { id: "html11-F097", title: "1. Apresentação do Módulo" },
                { id: "html11-F098", title: "2. O que é e como usar o Flexbox" },
                { id: "html11-F099", title: "3. Espaçamento entre os elementos" },
                { id: "html11-F100", title: "4. Mudar a direção do Flexbox" },
                { id: "html11-F101", title: "5. Tamanho dos elementos" },
                { id: "html11-F102", title: "6. Alinhamento e Posicionamento dos elementos" },
                { id: "html11-F103", title: "7. Desafio 1 - Construindo Layouts com Flexbox" },
                { id: "html11-F104", title: "8. Desafio 1 - Gabarito" },
                { id: "html11-F105", title: "9. Desafio 2 - Flexbox na Home da Hashtag" },
                { id: "html11-F106", title: "10. Desafio 2 - Flexbox no Cabeçalho" },
                { id: "html11-F107", title: "11. Desafio 2 - Flexbox na Seção Hero" },
                { id: "html11-F108", title: "12. Desafio 2 - Flexbox na Seção Conteúdos Gratuitos" },
                { id: "html11-F109", title: "13. Desafio 2 - Flexbox na Seção Diferenciais" },
                { id: "html11-F110", title: "14. Desafio 2 - Flexbox na Seção O que falam" },
                { id: "html11-F111", title: "15. Desafio 2 - Flexbox na Seção Na mídia" },
                { id: "html11-F112", title: "16. Desafio 2 - Flexbox na Blog da Hashtag" },
                { id: "html11-F113", title: "17. Desafio 2 - Flexbox na Seção Como ajudar" },
                { id: "html11-F114", title: "18. Desafio 2 - Flexbox na Seção Minicurso" },
                { id: "html11-F115", title: "19. Desafio 2 - Flexbox no Rodapé" }
            ],
        },
        {
            id: "html11-Module-8",
            title: "8. Componentes Personalizados no HTML",
            lessons: [
                { id: "html11-F116", title: "1. Apresentação do Módulo" },
                { id: "html11-F117", title: "2. Paginação - Apresentando o Desafio" },
                { id: "html11-F118", title: "3. Paginação - Resolução 12" },
                { id: "html11-F119", title: "4. Paginação - Resolução 22 + CSS Nesting" },
                { id: "html11-F120", title: "5. Acordeão - Apresentando o Desafio" },
                { id: "html11-F121", title: "6. Acordeão - Resolução" },
                { id: "html11-F122", title: "7. Popup - Apresentando o Desafio" },
                { id: "html11-F123", title: "8. Popup - Resolução" },
                { id: "html11-F124", title: "9. Carrossel - Apresentando o Desafio" },
                { id: "html11-F125", title: "10. Carrossel - Resolução 12" },
                { id: "html11-F126", title: "11. Carrossel - Resolução 22" },
                { id: "html11-F127", title: "12. Desafio 2 - Criando o Popup da Home da Hashtag" },
                { id: "html11-F128", title: "13. Desafio 2 - Gabarito" }
            ],
        },
        {
            id: "html11-Module-9",
            title: "9. Grid no CSS",
            lessons: [
                { id: "html11-F129", title: "1. Apresentação do Módulo" },
                { id: "html11-F130", title: "2. Como usar o Grid" },
                { id: "html11-F131", title: "3. Definindo as linhas da Grade" },
                { id: "html11-F132", title: "4. Definindo as colunas da Grade" },
                { id: "html11-F133", title: "5. Propriedade Grid" },
                { id: "html11-F134", title: "6. Posicionando os elementos" },
                { id: "html11-F135", title: "7. Espaçamento entre os elementos" },
                { id: "html11-F136", title: "8. Áreas dentro da Grade" },
                { id: "html11-F137", title: "9. Alinhamento dos elementos" },
                { id: "html11-F138", title: "10. Desafio 1 - Construindo um layout com Grid" },
                { id: "html11-F139", title: "11. Desafio 1 - Gabarito" },
                { id: "html11-F140", title: "12. Desafio 2 - Usando Grid na Seção Blog" },
                { id: "html11-F141", title: "13. Desafio 2 - Gabarito" }
            ],
        },
        {
            id: "html11-Module-10",
            title: "10. Animações e Efeitos no CSS",
            lessons: [
                { id: "html11-F142", title: "1. Apresentação do Módulo" },
                { id: "html11-F143", title: "2. Transições - 1-2" },
                { id: "html11-F144", title: "3. Transições - 2-2" },
                { id: "html11-F145", title: "4. Efeitos 2D" },
                { id: "html11-F146", title: "5. Efeitos 3D" },
                { id: "html11-F147", title: "6. Keyframes" },
                { id: "html11-F148", title: "7. Animation e suas propriedades" },
                { id: "html11-F149", title: "8. Desafio 1 - Criando um Elementos Animado" },
                { id: "html11-F150", title: "9. Desafio 1 - Gabarito" },
                { id: "html11-F151", title: "10. Desafio 2 - Transições na Home da Hashtag" },
                { id: "html11-F152", title: "11. Desafio 2 - Gabarito" }
            ],
        },
        {
            id: "html11-Module-11",
            title: "10. Checkpoint",
            lessons: [
                { id: "html11-F153", title: "1. O que vem pela frente" }
            ],
        },
        {
            id: "html11-Module-12",
            title: "11. Animações e Efeitos no CSS",
            lessons: [
                { id: "html11-F154", title: "1. Apresentação do Módulo" },
                { id: "html11-F155", title: "2. Transições - 1-2" },
                { id: "html11-F156", title: "3. Transições - 2-2" },
                { id: "html11-F157", title: "4. Efeitos 2D" },
                { id: "html11-F158", title: "5. Efeitos 3D" },
                { id: "html11-F159", title: "6. Keyframes" },
                { id: "html11-F160", title: "7. Animation e suas propriedades" },
                { id: "html11-F161", title: "8. Desafio 1 - Criando um Elementos Animado" },
                { id: "html11-F162", title: "9. Desafio 1 - Gabarito" },
                { id: "html11-F163", title: "10. Desafio 2 - Transições na Home da Hashtag" },
                { id: "html11-F164", title: "11. Desafio 2 - Gabarito" }
            ],
        },
        {
            id: "html11-Module-13",
            title: "11. Responsividade e Otimizações",
            lessons: [
                { id: "html11-F165", title: "1. Apresentação do Módulo" },
                { id: "html11-F166", title: "2. Media queries" },
                { id: "html11-F167", title: "3. Desktop x Mobile First" },
                { id: "html11-F168", title: "4. Escolhendo as Media Queries" },
                { id: "html11-F169", title: "5. Imagens responsivas - Tag Img - 12" },
                { id: "html11-F170", title: "6. O que é DPR" },
                { id: "html11-F171", title: "7. Imagens responsivas - Tag Img - 22" },
                { id: "html11-F172", title: "8. Imagens responsivas - Tag Picture" },
                { id: "html11-F173", title: "9. Imagens responsivas - CSS" },
                { id: "html11-F174", title: "10. Variáveis no CSS" },
                { id: "html11-F175", title: "11. Importando Fontes" },
                { id: "html11-F176", title: "12. Lazy Loading" },
                { id: "html11-F177", title: "13. Carregamento do CSS e Arquivos de Estilização" },
                { id: "html11-F178", title: "14. Desafio 2 - Deixando a Home da Hashtag responsiva" },
                { id: "html11-F179", title: "15. Desafio 2 - Criando a primeira Media Query" },
                { id: "html11-F180", title: "16. Desafio 2 - Alterando a página inteira mudando uma única coisa" },
                { id: "html11-F181", title: "17. Desafio 2 - Alterando o Layout da Seção Hero" },
                { id: "html11-F182", title: "18. Desafio 2 - Alterando o Layout da Seção Conteúdos Gratuitos" },
                { id: "html11-F183", title: "19. Desafio 2 - Alterando o Layout da Seção Diferenciais" },
                { id: "html11-F184", title: "20. Desafio 2 - Alterando o Layout da Seção O que falam" },
                { id: "html11-F185", title: "21. Desafio 2 - Alterando o Layout da Seção Na mídia" },
                { id: "html11-F186", title: "22. Desafio 2 - Alterando o Layout da Seção Blog" },
                { id: "html11-F187", title: "23. Desafio 2 - Finalizando o Layout da Media Query de 767 a 480" },
                { id: "html11-F188", title: "24. Desafio 2 - Última Media Query para a Seção Hero e Conteúdos" },
                { id: "html11-F189", title: "25. Desafio 2 - Última Media Query para as Seções Diferenciais, O que falam e Na mídia" },
                { id: "html11-F190", title: "26. Desafio 2 - Finalizando a última Media Query" },
                { id: "html11-F191", title: "27. Desafio 2 - Criando a Navegação Mobile" },
                { id: "html11-F192", title: "28. Desafio 2 - Finalizando a Navegação Mobile" },
                { id: "html11-F193", title: "29. Desafio 2 - Otimizando a Home da Hashtag" },
                { id: "html11-F194", title: "30. Desafio 2 - Deploy - Colocando a nossa página no ar" }
            ],
        },
        {
            id: "html11-Module-14",
            title: "12. Float no CSS",
            lessons: [
                { id: "html11-F195", title: "1. Apresentação do Módulo" },
                { id: "html11-F196", title: "2. Como usar as propriedades float e clear" },
                { id: "html11-F197", title: "3. Desafio - Construindo um layout com float" },
                { id: "html11-F198", title: "4. Desafio - Gabarito" }
            ],
        },
        {
            id: "html11-Module-15",
            title: "12. Responsividade e Otimizações",
            lessons: [
                { id: "html11-F199", title: "1. Apresentação do Módulo" },
                { id: "html11-F200", title: "2. Media queries" },
                { id: "html11-F201", title: "3. Desktop x Mobile First" },
                { id: "html11-F202", title: "4. Escolhendo as Media Queries" },
                { id: "html11-F203", title: "5. Imagens responsivas - Tag Img - 12" },
                { id: "html11-F204", title: "6. O que é DPR" },
                { id: "html11-F205", title: "7. Imagens responsivas - Tag Img - 22" },
                { id: "html11-F206", title: "8. Imagens responsivas - Tag Picture" },
                { id: "html11-F207", title: "9. Imagens responsivas - CSS" },
                { id: "html11-F208", title: "10. Variáveis no CSS" },
                { id: "html11-F209", title: "11. Importando Fontes" },
                { id: "html11-F210", title: "12. Lazy Loading" },
                { id: "html11-F211", title: "13. Carregamento do CSS e Arquivos de Estilização" },
                { id: "html11-F212", title: "14. Desafio 2 - Deixando a Home da Hashtag responsiva" },
                { id: "html11-F213", title: "15. Desafio 2 - Criando a primeira Media Query" },
                { id: "html11-F214", title: "16. Desafio 2 - Alterando a página inteira mudando uma única coisa" },
                { id: "html11-F215", title: "17. Desafio 2 - Alterando o Layout da Seção Hero" },
                { id: "html11-F216", title: "18. Desafio 2 - Alterando o Layout da Seção Conteúdos Gratuitos" },
                { id: "html11-F217", title: "19. Desafio 2 - Alterando o Layout da Seção Diferenciais" },
                { id: "html11-F218", title: "20. Desafio 2 - Alterando o Layout da Seção O que falam" },
                { id: "html11-F219", title: "21. Desafio 2 - Alterando o Layout da Seção Na mídia" },
                { id: "html11-F220", title: "22. Desafio 2 - Alterando o Layout da Seção Blog" },
                { id: "html11-F221", title: "23. Desafio 2 - Finalizando o Layout da Media Query de 767 a 480" },
                { id: "html11-F222", title: "24. Desafio 2 - Última Media Query para a Seção Hero e Conteúdos" },
                { id: "html11-F223", title: "25. Desafio 2 - Última Media Query para as Seções Diferenciais, O que falam e Na mídia" },
                { id: "html11-F224", title: "26. Desafio 2 - Finalizando a última Media Query" },
                { id: "html11-F225", title: "27. Desafio 2 - Criando a Navegação Mobile" },
                { id: "html11-F226", title: "28. Desafio 2 - Finalizando a Navegação Mobile" },
                { id: "html11-F227", title: "29. Desafio 2 - Otimizando a Home da Hashtag" },
                { id: "html11-F228", title: "30. Desafio 2 - Deploy - Colocando a nossa página no ar" }
            ],
        },
        {
            id: "html11-Module-16",
            title: "13. Float no CSS",
            lessons: [
                { id: "html11-F229", title: "1. Apresentação do Módulo" },
                { id: "html11-F230", title: "2. Como usar as propriedades float e clear" },
                { id: "html11-F231", title: "3. Desafio - Construindo um layout com float" },
                { id: "html11-F232", title: "4. Desafio - Gabarito" }
            ],
        },
        {
            id: "html11-Module-17",
            title: "13. Metodologia BEM",
            lessons: [
                { id: "html11-F233", title: "1. Apresentação do Módulo" },
                { id: "html11-F234", title: "2. Como funciona a Metodologia" },
                { id: "html11-F235", title: "3. Exemplos da Metotologia" },
                { id: "html11-F236", title: "4. Vantagens, Desvantagens e Conclusão" },
                { id: "html11-F237", title: "5. Cuidados e Observações" },
                { id: "html11-F238", title: "5. Cuidados e Observações" },
                { id: "html11-F239", title: "6. Exemplo prático" },
                { id: "html11-F240", title: "7. Desafio - Apresentação" },
                { id: "html11-F241", title: "8. Desafio - Gabarito" }
            ],
        },
        {
            id: "html11-Module-18",
            title: "14. Extensão - SASS",
            lessons: [
                { id: "html11-F242", title: "1. Apresentação do Módulo" }
            ],
        },
        {
            id: "html11-Module-19",
            title: "14. Metodologia BEM",
            lessons: [
                { id: "html11-F243", title: "1. Apresentação do Módulo" },
                { id: "html11-F244", title: "2. Como funciona a Metodologia" },
                { id: "html11-F245", title: "3. Exemplos da Metotologia" },
                { id: "html11-F246", title: "4. Vantagens, Desvantagens e Conclusão" },
                { id: "html11-F247", title: "5. Cuidados e Observações" },
                { id: "html11-F248", title: "6. Exemplo prático" },
                { id: "html11-F249", title: "7. Desafio - Apresentação" },
                { id: "html11-F250", title: "8. Desafio - Gabarito" }
            ],
        },
        {
            id: "html11-Module-20",
            title: "15. Extensão - SASS",
            lessons: [
                { id: "html11-F251", title: "1. Apresentação do Módulo" },
                { id: "html11-F252", title: "2. O que é SASS" },
                { id: "html11-F253", title: "3. O que é NodeJS e o que é NPM" },
                { id: "html11-F254", title: "4. Instalando o NodeJS, NPM e SASS" },
                { id: "html11-F255", title: "5. Criando e compilando nosso primeiro código" },
                { id: "html11-F256", title: "6. Variáveis" },
                { id: "html11-F257", title: "7. Nesting x Native Nesting" },
                { id: "html11-F258", title: "8. Functions" },
                { id: "html11-F259", title: "9. Mixins e Includes" },
                { id: "html11-F260", title: "10. Extends" },
                { id: "html11-F261", title: "11. Content e If" },
                { id: "html11-F262", title: "12. Build Compile, Prefix and Compress" },
                { id: "html11-F263", title: "13. Padrão 7-1" }
            ],
        }
    ]
};
